CREATE TABLE IF NOT EXISTS public.employee_data
(
    tenant_uuid uuid NOT NULL,
    employee_id text COLLATE pg_catalog."default" NOT NULL,
    first_name text COLLATE pg_catalog."default",
    middle_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default",
    birth_date date,
    gender text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    phone_number text COLLATE pg_catalog."default",
    postal_code text COLLATE pg_catalog."default",
    address_perfecture text COLLATE pg_catalog."default",
    address_district text COLLATE pg_catalog."default",
    address_number text COLLATE pg_catalog."default",
    address_building text COLLATE pg_catalog."default",
    hire_date date,
    termination_date date,
    job_title text COLLATE pg_catalog."default",
    department text COLLATE pg_catalog."default",
    salary numeric(12,2),
    salary_currency text COLLATE pg_catalog."default",
    nationality text COLLATE pg_catalog."default",
    emergency_contact_name text COLLATE pg_catalog."default",
    emergency_contact_number text COLLATE pg_catalog."default",
    visa_expiry_date date,
    work_permit_expiry_date date,
    custom_field_26 text COLLATE pg_catalog."default",
    custom_field_27 text COLLATE pg_catalog."default",
    custom_field_28 text COLLATE pg_catalog."default",
    custom_field_29 text COLLATE pg_catalog."default",
    custom_field_30 text COLLATE pg_catalog."default",
    custom_field_31 text COLLATE pg_catalog."default",
    custom_field_32 text COLLATE pg_catalog."default",
    custom_field_33 text COLLATE pg_catalog."default",
    custom_field_34 text COLLATE pg_catalog."default",
    custom_field_35 text COLLATE pg_catalog."default",
    custom_field_36 text COLLATE pg_catalog."default",
    custom_field_37 text COLLATE pg_catalog."default",
    custom_field_38 text COLLATE pg_catalog."default",
    custom_field_39 text COLLATE pg_catalog."default",
    custom_field_40 text COLLATE pg_catalog."default",
    custom_field_41 text COLLATE pg_catalog."default",
    custom_field_42 text COLLATE pg_catalog."default",
    custom_field_43 text COLLATE pg_catalog."default",
    custom_field_44 text COLLATE pg_catalog."default",
    custom_field_45 text COLLATE pg_catalog."default",
    custom_field_46 text COLLATE pg_catalog."default",
    custom_field_47 text COLLATE pg_catalog."default",
    custom_field_48 text COLLATE pg_catalog."default",
    custom_field_49 text COLLATE pg_catalog."default",
    custom_field_50 text COLLATE pg_catalog."default",
    custom_field_51 text COLLATE pg_catalog."default",
    custom_field_52 text COLLATE pg_catalog."default",
    custom_field_53 text COLLATE pg_catalog."default",
    custom_field_54 text COLLATE pg_catalog."default",
    custom_field_55 text COLLATE pg_catalog."default",
    custom_field_56 text COLLATE pg_catalog."default",
    custom_field_57 text COLLATE pg_catalog."default",
    custom_field_58 text COLLATE pg_catalog."default",
    custom_field_59 text COLLATE pg_catalog."default",
    custom_field_60 text COLLATE pg_catalog."default",
    custom_field_61 text COLLATE pg_catalog."default",
    custom_field_62 text COLLATE pg_catalog."default",
    custom_field_63 text COLLATE pg_catalog."default",
    custom_field_64 text COLLATE pg_catalog."default",
    custom_field_65 text COLLATE pg_catalog."default",
    custom_field_66 text COLLATE pg_catalog."default",
    custom_field_67 text COLLATE pg_catalog."default",
    custom_field_68 text COLLATE pg_catalog."default",
    custom_field_69 text COLLATE pg_catalog."default",
    custom_field_70 text COLLATE pg_catalog."default",
    custom_field_71 text COLLATE pg_catalog."default",
    custom_field_72 text COLLATE pg_catalog."default",
    custom_field_73 text COLLATE pg_catalog."default",
    custom_field_74 text COLLATE pg_catalog."default",
    custom_field_75 text COLLATE pg_catalog."default",
    custom_field_76 text COLLATE pg_catalog."default",
    custom_field_77 text COLLATE pg_catalog."default",
    custom_field_78 text COLLATE pg_catalog."default",
    custom_field_79 text COLLATE pg_catalog."default",
    custom_field_80 text COLLATE pg_catalog."default",
    custom_field_81 text COLLATE pg_catalog."default",
    custom_field_82 text COLLATE pg_catalog."default",
    custom_field_83 text COLLATE pg_catalog."default",
    custom_field_84 text COLLATE pg_catalog."default",
    custom_field_85 text COLLATE pg_catalog."default",
    custom_field_86 text COLLATE pg_catalog."default",
    custom_field_87 text COLLATE pg_catalog."default",
    custom_field_88 text COLLATE pg_catalog."default",
    custom_field_89 text COLLATE pg_catalog."default",
    custom_field_90 text COLLATE pg_catalog."default",
    custom_field_91 text COLLATE pg_catalog."default",
    custom_field_92 text COLLATE pg_catalog."default",
    custom_field_93 text COLLATE pg_catalog."default",
    custom_field_94 text COLLATE pg_catalog."default",
    custom_field_95 text COLLATE pg_catalog."default",
    custom_field_96 text COLLATE pg_catalog."default",
    custom_field_97 text COLLATE pg_catalog."default",
    custom_field_98 text COLLATE pg_catalog."default",
    custom_field_99 text COLLATE pg_catalog."default",
    custom_field_100 text COLLATE pg_catalog."default",
    CONSTRAINT employee_data_pkey PRIMARY KEY (tenant_uuid, employee_id)
);